// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"mime/multipart"
	"time"

	"github.com/markhc/isrv/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDatabase creates a new instance of MockDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatabase {
	mock := &MockDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDatabase is an autogenerated mock type for the Database type
type MockDatabase struct {
	mock.Mock
}

type MockDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatabase) EXPECT() *MockDatabase_Expecter {
	return &MockDatabase_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockDatabase
func (_mock *MockDatabase) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatabase_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDatabase_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDatabase_Expecter) Close() *MockDatabase_Close_Call {
	return &MockDatabase_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDatabase_Close_Call) Run(run func()) *MockDatabase_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDatabase_Close_Call) Return(err error) *MockDatabase_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatabase_Close_Call) RunAndReturn(run func() error) *MockDatabase_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Connect provides a mock function for the type MockDatabase
func (_mock *MockDatabase) Connect() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatabase_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockDatabase_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
func (_e *MockDatabase_Expecter) Connect() *MockDatabase_Connect_Call {
	return &MockDatabase_Connect_Call{Call: _e.mock.On("Connect")}
}

func (_c *MockDatabase_Connect_Call) Run(run func()) *MockDatabase_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDatabase_Connect_Call) Return(err error) *MockDatabase_Connect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatabase_Connect_Call) RunAndReturn(run func() error) *MockDatabase_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// GetExpiredFiles provides a mock function for the type MockDatabase
func (_mock *MockDatabase) GetExpiredFiles(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetExpiredFiles")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatabase_GetExpiredFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpiredFiles'
type MockDatabase_GetExpiredFiles_Call struct {
	*mock.Call
}

// GetExpiredFiles is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatabase_Expecter) GetExpiredFiles(ctx interface{}) *MockDatabase_GetExpiredFiles_Call {
	return &MockDatabase_GetExpiredFiles_Call{Call: _e.mock.On("GetExpiredFiles", ctx)}
}

func (_c *MockDatabase_GetExpiredFiles_Call) Run(run func(ctx context.Context)) *MockDatabase_GetExpiredFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDatabase_GetExpiredFiles_Call) Return(strings []string, err error) *MockDatabase_GetExpiredFiles_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockDatabase_GetExpiredFiles_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockDatabase_GetExpiredFiles_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileByToken provides a mock function for the type MockDatabase
func (_mock *MockDatabase) GetFileByToken(ctx context.Context, token string) (string, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetFileByToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatabase_GetFileByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileByToken'
type MockDatabase_GetFileByToken_Call struct {
	*mock.Call
}

// GetFileByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockDatabase_Expecter) GetFileByToken(ctx interface{}, token interface{}) *MockDatabase_GetFileByToken_Call {
	return &MockDatabase_GetFileByToken_Call{Call: _e.mock.On("GetFileByToken", ctx, token)}
}

func (_c *MockDatabase_GetFileByToken_Call) Run(run func(ctx context.Context, token string)) *MockDatabase_GetFileByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabase_GetFileByToken_Call) Return(s string, err error) *MockDatabase_GetFileByToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockDatabase_GetFileByToken_Call) RunAndReturn(run func(ctx context.Context, token string) (string, error)) *MockDatabase_GetFileByToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileData provides a mock function for the type MockDatabase
func (_mock *MockDatabase) GetFileData(ctx context.Context, fileID string) (*models.File, error) {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for GetFileData")
	}

	var r0 *models.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.File, error)); ok {
		return returnFunc(ctx, fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.File); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatabase_GetFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileData'
type MockDatabase_GetFileData_Call struct {
	*mock.Call
}

// GetFileData is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID string
func (_e *MockDatabase_Expecter) GetFileData(ctx interface{}, fileID interface{}) *MockDatabase_GetFileData_Call {
	return &MockDatabase_GetFileData_Call{Call: _e.mock.On("GetFileData", ctx, fileID)}
}

func (_c *MockDatabase_GetFileData_Call) Run(run func(ctx context.Context, fileID string)) *MockDatabase_GetFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabase_GetFileData_Call) Return(file *models.File, err error) *MockDatabase_GetFileData_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockDatabase_GetFileData_Call) RunAndReturn(run func(ctx context.Context, fileID string) (*models.File, error)) *MockDatabase_GetFileData_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileMetadata provides a mock function for the type MockDatabase
func (_mock *MockDatabase) GetFileMetadata(ctx context.Context, fileID string) (map[string]string, error) {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for GetFileMetadata")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return returnFunc(ctx, fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatabase_GetFileMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileMetadata'
type MockDatabase_GetFileMetadata_Call struct {
	*mock.Call
}

// GetFileMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID string
func (_e *MockDatabase_Expecter) GetFileMetadata(ctx interface{}, fileID interface{}) *MockDatabase_GetFileMetadata_Call {
	return &MockDatabase_GetFileMetadata_Call{Call: _e.mock.On("GetFileMetadata", ctx, fileID)}
}

func (_c *MockDatabase_GetFileMetadata_Call) Run(run func(ctx context.Context, fileID string)) *MockDatabase_GetFileMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabase_GetFileMetadata_Call) Return(stringToString map[string]string, err error) *MockDatabase_GetFileMetadata_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *MockDatabase_GetFileMetadata_Call) RunAndReturn(run func(ctx context.Context, fileID string) (map[string]string, error)) *MockDatabase_GetFileMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileToken provides a mock function for the type MockDatabase
func (_mock *MockDatabase) GetFileToken(ctx context.Context, fileID string) (string, error) {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for GetFileToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatabase_GetFileToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileToken'
type MockDatabase_GetFileToken_Call struct {
	*mock.Call
}

// GetFileToken is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID string
func (_e *MockDatabase_Expecter) GetFileToken(ctx interface{}, fileID interface{}) *MockDatabase_GetFileToken_Call {
	return &MockDatabase_GetFileToken_Call{Call: _e.mock.On("GetFileToken", ctx, fileID)}
}

func (_c *MockDatabase_GetFileToken_Call) Run(run func(ctx context.Context, fileID string)) *MockDatabase_GetFileToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabase_GetFileToken_Call) Return(s string, err error) *MockDatabase_GetFileToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockDatabase_GetFileToken_Call) RunAndReturn(run func(ctx context.Context, fileID string) (string, error)) *MockDatabase_GetFileToken_Call {
	_c.Call.Return(run)
	return _c
}

// Migrate provides a mock function for the type MockDatabase
func (_mock *MockDatabase) Migrate() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Migrate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatabase_Migrate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Migrate'
type MockDatabase_Migrate_Call struct {
	*mock.Call
}

// Migrate is a helper method to define mock.On call
func (_e *MockDatabase_Expecter) Migrate() *MockDatabase_Migrate_Call {
	return &MockDatabase_Migrate_Call{Call: _e.mock.On("Migrate")}
}

func (_c *MockDatabase_Migrate_Call) Run(run func()) *MockDatabase_Migrate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDatabase_Migrate_Call) Return(err error) *MockDatabase_Migrate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatabase_Migrate_Call) RunAndReturn(run func() error) *MockDatabase_Migrate_Call {
	_c.Call.Return(run)
	return _c
}

// OnFileDelete provides a mock function for the type MockDatabase
func (_mock *MockDatabase) OnFileDelete(ctx context.Context, fileID string) error {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for OnFileDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatabase_OnFileDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnFileDelete'
type MockDatabase_OnFileDelete_Call struct {
	*mock.Call
}

// OnFileDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID string
func (_e *MockDatabase_Expecter) OnFileDelete(ctx interface{}, fileID interface{}) *MockDatabase_OnFileDelete_Call {
	return &MockDatabase_OnFileDelete_Call{Call: _e.mock.On("OnFileDelete", ctx, fileID)}
}

func (_c *MockDatabase_OnFileDelete_Call) Run(run func(ctx context.Context, fileID string)) *MockDatabase_OnFileDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabase_OnFileDelete_Call) Return(err error) *MockDatabase_OnFileDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatabase_OnFileDelete_Call) RunAndReturn(run func(ctx context.Context, fileID string) error) *MockDatabase_OnFileDelete_Call {
	_c.Call.Return(run)
	return _c
}

// OnFileDownload provides a mock function for the type MockDatabase
func (_mock *MockDatabase) OnFileDownload(ctx context.Context, fileID string) error {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for OnFileDownload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatabase_OnFileDownload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnFileDownload'
type MockDatabase_OnFileDownload_Call struct {
	*mock.Call
}

// OnFileDownload is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID string
func (_e *MockDatabase_Expecter) OnFileDownload(ctx interface{}, fileID interface{}) *MockDatabase_OnFileDownload_Call {
	return &MockDatabase_OnFileDownload_Call{Call: _e.mock.On("OnFileDownload", ctx, fileID)}
}

func (_c *MockDatabase_OnFileDownload_Call) Run(run func(ctx context.Context, fileID string)) *MockDatabase_OnFileDownload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabase_OnFileDownload_Call) Return(err error) *MockDatabase_OnFileDownload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatabase_OnFileDownload_Call) RunAndReturn(run func(ctx context.Context, fileID string) error) *MockDatabase_OnFileDownload_Call {
	_c.Call.Return(run)
	return _c
}

// OnFileUpload provides a mock function for the type MockDatabase
func (_mock *MockDatabase) OnFileUpload(ctx context.Context, fileID string, fileHeader *multipart.FileHeader, token string, expirationTime time.Time, ipAddress string) error {
	ret := _mock.Called(ctx, fileID, fileHeader, token, expirationTime, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for OnFileUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *multipart.FileHeader, string, time.Time, string) error); ok {
		r0 = returnFunc(ctx, fileID, fileHeader, token, expirationTime, ipAddress)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatabase_OnFileUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnFileUpload'
type MockDatabase_OnFileUpload_Call struct {
	*mock.Call
}

// OnFileUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID string
//   - fileHeader *multipart.FileHeader
//   - token string
//   - expirationTime time.Time
//   - ipAddress string
func (_e *MockDatabase_Expecter) OnFileUpload(ctx interface{}, fileID interface{}, fileHeader interface{}, token interface{}, expirationTime interface{}, ipAddress interface{}) *MockDatabase_OnFileUpload_Call {
	return &MockDatabase_OnFileUpload_Call{Call: _e.mock.On("OnFileUpload", ctx, fileID, fileHeader, token, expirationTime, ipAddress)}
}

func (_c *MockDatabase_OnFileUpload_Call) Run(run func(ctx context.Context, fileID string, fileHeader *multipart.FileHeader, token string, expirationTime time.Time, ipAddress string)) *MockDatabase_OnFileUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *multipart.FileHeader
		if args[2] != nil {
			arg2 = args[2].(*multipart.FileHeader)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockDatabase_OnFileUpload_Call) Return(err error) *MockDatabase_OnFileUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatabase_OnFileUpload_Call) RunAndReturn(run func(ctx context.Context, fileID string, fileHeader *multipart.FileHeader, token string, expirationTime time.Time, ipAddress string) error) *MockDatabase_OnFileUpload_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockDatabase
func (_mock *MockDatabase) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatabase_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockDatabase_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatabase_Expecter) Ping(ctx interface{}) *MockDatabase_Ping_Call {
	return &MockDatabase_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockDatabase_Ping_Call) Run(run func(ctx context.Context)) *MockDatabase_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDatabase_Ping_Call) Return(err error) *MockDatabase_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatabase_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockDatabase_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// SetExpiration provides a mock function for the type MockDatabase
func (_mock *MockDatabase) SetExpiration(ctx context.Context, fileID string, expiration time.Time) error {
	ret := _mock.Called(ctx, fileID, expiration)

	if len(ret) == 0 {
		panic("no return value specified for SetExpiration")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = returnFunc(ctx, fileID, expiration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatabase_SetExpiration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetExpiration'
type MockDatabase_SetExpiration_Call struct {
	*mock.Call
}

// SetExpiration is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID string
//   - expiration time.Time
func (_e *MockDatabase_Expecter) SetExpiration(ctx interface{}, fileID interface{}, expiration interface{}) *MockDatabase_SetExpiration_Call {
	return &MockDatabase_SetExpiration_Call{Call: _e.mock.On("SetExpiration", ctx, fileID, expiration)}
}

func (_c *MockDatabase_SetExpiration_Call) Run(run func(ctx context.Context, fileID string, expiration time.Time)) *MockDatabase_SetExpiration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDatabase_SetExpiration_Call) Return(err error) *MockDatabase_SetExpiration_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatabase_SetExpiration_Call) RunAndReturn(run func(ctx context.Context, fileID string, expiration time.Time) error) *MockDatabase_SetExpiration_Call {
	_c.Call.Return(run)
	return _c
}
