// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"mime/multipart"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDatabase creates a new instance of MockDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatabase {
	mock := &MockDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDatabase is an autogenerated mock type for the Database type
type MockDatabase struct {
	mock.Mock
}

type MockDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatabase) EXPECT() *MockDatabase_Expecter {
	return &MockDatabase_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockDatabase
func (_mock *MockDatabase) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatabase_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDatabase_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDatabase_Expecter) Close() *MockDatabase_Close_Call {
	return &MockDatabase_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDatabase_Close_Call) Run(run func()) *MockDatabase_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDatabase_Close_Call) Return(err error) *MockDatabase_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatabase_Close_Call) RunAndReturn(run func() error) *MockDatabase_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Connect provides a mock function for the type MockDatabase
func (_mock *MockDatabase) Connect() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatabase_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockDatabase_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
func (_e *MockDatabase_Expecter) Connect() *MockDatabase_Connect_Call {
	return &MockDatabase_Connect_Call{Call: _e.mock.On("Connect")}
}

func (_c *MockDatabase_Connect_Call) Run(run func()) *MockDatabase_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDatabase_Connect_Call) Return(err error) *MockDatabase_Connect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatabase_Connect_Call) RunAndReturn(run func() error) *MockDatabase_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// GetExpiredFiles provides a mock function for the type MockDatabase
func (_mock *MockDatabase) GetExpiredFiles() ([]string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetExpiredFiles")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatabase_GetExpiredFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpiredFiles'
type MockDatabase_GetExpiredFiles_Call struct {
	*mock.Call
}

// GetExpiredFiles is a helper method to define mock.On call
func (_e *MockDatabase_Expecter) GetExpiredFiles() *MockDatabase_GetExpiredFiles_Call {
	return &MockDatabase_GetExpiredFiles_Call{Call: _e.mock.On("GetExpiredFiles")}
}

func (_c *MockDatabase_GetExpiredFiles_Call) Run(run func()) *MockDatabase_GetExpiredFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDatabase_GetExpiredFiles_Call) Return(strings []string, err error) *MockDatabase_GetExpiredFiles_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockDatabase_GetExpiredFiles_Call) RunAndReturn(run func() ([]string, error)) *MockDatabase_GetExpiredFiles_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileMetadata provides a mock function for the type MockDatabase
func (_mock *MockDatabase) GetFileMetadata(fileID string) (map[string]string, error) {
	ret := _mock.Called(fileID)

	if len(ret) == 0 {
		panic("no return value specified for GetFileMetadata")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (map[string]string, error)); ok {
		return returnFunc(fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) map[string]string); ok {
		r0 = returnFunc(fileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatabase_GetFileMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileMetadata'
type MockDatabase_GetFileMetadata_Call struct {
	*mock.Call
}

// GetFileMetadata is a helper method to define mock.On call
//   - fileID string
func (_e *MockDatabase_Expecter) GetFileMetadata(fileID interface{}) *MockDatabase_GetFileMetadata_Call {
	return &MockDatabase_GetFileMetadata_Call{Call: _e.mock.On("GetFileMetadata", fileID)}
}

func (_c *MockDatabase_GetFileMetadata_Call) Run(run func(fileID string)) *MockDatabase_GetFileMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDatabase_GetFileMetadata_Call) Return(stringToString map[string]string, err error) *MockDatabase_GetFileMetadata_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *MockDatabase_GetFileMetadata_Call) RunAndReturn(run func(fileID string) (map[string]string, error)) *MockDatabase_GetFileMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// Migrate provides a mock function for the type MockDatabase
func (_mock *MockDatabase) Migrate() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Migrate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatabase_Migrate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Migrate'
type MockDatabase_Migrate_Call struct {
	*mock.Call
}

// Migrate is a helper method to define mock.On call
func (_e *MockDatabase_Expecter) Migrate() *MockDatabase_Migrate_Call {
	return &MockDatabase_Migrate_Call{Call: _e.mock.On("Migrate")}
}

func (_c *MockDatabase_Migrate_Call) Run(run func()) *MockDatabase_Migrate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDatabase_Migrate_Call) Return(err error) *MockDatabase_Migrate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatabase_Migrate_Call) RunAndReturn(run func() error) *MockDatabase_Migrate_Call {
	_c.Call.Return(run)
	return _c
}

// OnFileDelete provides a mock function for the type MockDatabase
func (_mock *MockDatabase) OnFileDelete(fileID string) error {
	ret := _mock.Called(fileID)

	if len(ret) == 0 {
		panic("no return value specified for OnFileDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(fileID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatabase_OnFileDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnFileDelete'
type MockDatabase_OnFileDelete_Call struct {
	*mock.Call
}

// OnFileDelete is a helper method to define mock.On call
//   - fileID string
func (_e *MockDatabase_Expecter) OnFileDelete(fileID interface{}) *MockDatabase_OnFileDelete_Call {
	return &MockDatabase_OnFileDelete_Call{Call: _e.mock.On("OnFileDelete", fileID)}
}

func (_c *MockDatabase_OnFileDelete_Call) Run(run func(fileID string)) *MockDatabase_OnFileDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDatabase_OnFileDelete_Call) Return(err error) *MockDatabase_OnFileDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatabase_OnFileDelete_Call) RunAndReturn(run func(fileID string) error) *MockDatabase_OnFileDelete_Call {
	_c.Call.Return(run)
	return _c
}

// OnFileDownload provides a mock function for the type MockDatabase
func (_mock *MockDatabase) OnFileDownload(fileID string) error {
	ret := _mock.Called(fileID)

	if len(ret) == 0 {
		panic("no return value specified for OnFileDownload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(fileID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatabase_OnFileDownload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnFileDownload'
type MockDatabase_OnFileDownload_Call struct {
	*mock.Call
}

// OnFileDownload is a helper method to define mock.On call
//   - fileID string
func (_e *MockDatabase_Expecter) OnFileDownload(fileID interface{}) *MockDatabase_OnFileDownload_Call {
	return &MockDatabase_OnFileDownload_Call{Call: _e.mock.On("OnFileDownload", fileID)}
}

func (_c *MockDatabase_OnFileDownload_Call) Run(run func(fileID string)) *MockDatabase_OnFileDownload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDatabase_OnFileDownload_Call) Return(err error) *MockDatabase_OnFileDownload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatabase_OnFileDownload_Call) RunAndReturn(run func(fileID string) error) *MockDatabase_OnFileDownload_Call {
	_c.Call.Return(run)
	return _c
}

// OnFileUpload provides a mock function for the type MockDatabase
func (_mock *MockDatabase) OnFileUpload(fileID string, fileHeader *multipart.FileHeader, expirationTime time.Time, ipAddress string) error {
	ret := _mock.Called(fileID, fileHeader, expirationTime, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for OnFileUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, *multipart.FileHeader, time.Time, string) error); ok {
		r0 = returnFunc(fileID, fileHeader, expirationTime, ipAddress)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatabase_OnFileUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnFileUpload'
type MockDatabase_OnFileUpload_Call struct {
	*mock.Call
}

// OnFileUpload is a helper method to define mock.On call
//   - fileID string
//   - fileHeader *multipart.FileHeader
//   - expirationTime time.Time
//   - ipAddress string
func (_e *MockDatabase_Expecter) OnFileUpload(fileID interface{}, fileHeader interface{}, expirationTime interface{}, ipAddress interface{}) *MockDatabase_OnFileUpload_Call {
	return &MockDatabase_OnFileUpload_Call{Call: _e.mock.On("OnFileUpload", fileID, fileHeader, expirationTime, ipAddress)}
}

func (_c *MockDatabase_OnFileUpload_Call) Run(run func(fileID string, fileHeader *multipart.FileHeader, expirationTime time.Time, ipAddress string)) *MockDatabase_OnFileUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *multipart.FileHeader
		if args[1] != nil {
			arg1 = args[1].(*multipart.FileHeader)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDatabase_OnFileUpload_Call) Return(err error) *MockDatabase_OnFileUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatabase_OnFileUpload_Call) RunAndReturn(run func(fileID string, fileHeader *multipart.FileHeader, expirationTime time.Time, ipAddress string) error) *MockDatabase_OnFileUpload_Call {
	_c.Call.Return(run)
	return _c
}
