{{- if include "isrv.createSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "isrv.fullname" . }}
  labels:
    {{- include "isrv.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secrets.adminUsername }}
  ISRV_ADMIN_USERNAME: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.adminPassword }}
  ISRV_ADMIN_PASSWORD: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.adminSessionSecret }}
  ISRV_ADMIN_SESSION_SECRET: {{ . | quote }}
  {{- end }}
  {{- with .Values.storage.accessKey }}
  ISRV_STORAGE_ACCESS_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.storage.secretKey }}
  ISRV_STORAGE_SECRET_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.cluster.ipHashSecret }}
  ISRV_CLUSTER_IP_HASH_SECRET: {{ . | quote }}
  {{- end }}
  {{- with .Values.cluster.redis.password }}
  ISRV_CLUSTER_REDIS_PASSWORD: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.databasePassword }}
  ISRV_DATABASE_PASSWORD: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.encryptionIdentity }}
  ISRV_ENCRYPTION_IDENTITY: {{ . | quote }}
  {{- end }}
{{- end }}
