package telemetry

import (
	"context"
	"fmt"

	"github.com/markhc/isrv/internal/models"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/exporters/otlp/otlplog/otlploghttp"
	"go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp"
	"go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp"
	"go.opentelemetry.io/otel/log/global"
	"go.opentelemetry.io/otel/propagation"
	sdklog "go.opentelemetry.io/otel/sdk/log"
	sdkmetric "go.opentelemetry.io/otel/sdk/metric"
	"go.opentelemetry.io/otel/sdk/resource"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
	semconv "go.opentelemetry.io/otel/semconv/v1.26.0"
	"go.opentelemetry.io/otel/trace"
)

// InstrumentationName is the OpenTelemetry instrumentation scope name used for
// all spans and metrics created directly by this application's code (as opposed
// to auto-instrumented HTTP spans generated by otelhttp).
const InstrumentationName = "github.com/markhc/isrv"

// Tracer returns the application tracer scoped to InstrumentationName.
// Use this to create spans inside handlers and other application code.
//
//nolint:ireturn // trace.Tracer is the OTel API contract; returning the concrete type would couple callers to the SDK
func Tracer() trace.Tracer {
	return otel.Tracer(InstrumentationName)
}

// ShutdownFunc flushes and shuts down all telemetry pipelines.
// It must be called before the process exits to ensure all buffered
// spans and metrics are flushed to the OTLP backend.
type ShutdownFunc func(context.Context) error

// Setup initialises the global OpenTelemetry tracer, meter, and logger providers
// and registers them as the OTel global instances.
//
// Exporter configuration (endpoint, auth headers, protocol) is read entirely
// from the standard OTEL_* environment variables, making the implementation
// backend-agnostic. Notable variables:
//
//   - OTEL_EXPORTER_OTLP_ENDPOINT  – base URL of the OTLP receiver
//   - OTEL_EXPORTER_OTLP_HEADERS   – comma-separated key=value auth headers
//   - OTEL_SERVICE_NAME             – overrides the default service.name
//   - OTEL_RESOURCE_ATTRIBUTES      – additional resource key=value pairs
//
// buildVersion is used as the default value for the service.version resource
// attribute and can be overridden via OTEL_RESOURCE_ATTRIBUTES.
//
// If telemetry is disabled in the configuration, Setup is a no-op and returns
// a no-op shutdown function.
//
// The caller is responsible for calling the returned ShutdownFunc to flush all
// buffered telemetry data before the process exits.
//
//nolint:funlen
func Setup(ctx context.Context, cfg models.TelemetryConfiguration, buildVersion string) (ShutdownFunc, error) {
	if !cfg.Enabled {
		return func(context.Context) error { return nil }, nil
	}

	res, err := resource.New(ctx,
		resource.WithAttributes(
			semconv.ServiceName("isrv"),
			semconv.ServiceVersion(buildVersion),
		),
		resource.WithFromEnv(),
		resource.WithTelemetrySDK(),
		resource.WithProcess(),
	)
	if err != nil {
		return nil, fmt.Errorf("create OTel resource: %w", err)
	}

	traceExporter, err := otlptracehttp.New(ctx)
	if err != nil {
		return nil, fmt.Errorf("create trace exporter: %w", err)
	}

	tp := sdktrace.NewTracerProvider(
		sdktrace.WithBatcher(traceExporter),
		sdktrace.WithResource(res),
	)

	metricExporter, err := otlpmetrichttp.New(ctx)
	if err != nil {
		_ = tp.Shutdown(ctx)

		return nil, fmt.Errorf("create metric exporter: %w", err)
	}

	mp := sdkmetric.NewMeterProvider(
		sdkmetric.WithReader(sdkmetric.NewPeriodicReader(metricExporter)),
		sdkmetric.WithResource(res),
	)

	logExporter, err := otlploghttp.New(ctx)
	if err != nil {
		_ = tp.Shutdown(ctx)
		_ = mp.Shutdown(ctx)

		return nil, fmt.Errorf("create log exporter: %w", err)
	}

	lp := sdklog.NewLoggerProvider(
		sdklog.WithProcessor(sdklog.NewBatchProcessor(logExporter)),
		sdklog.WithResource(res),
	)

	otel.SetTracerProvider(tp)
	otel.SetMeterProvider(mp)
	global.SetLoggerProvider(lp)
	otel.SetTextMapPropagator(propagation.NewCompositeTextMapPropagator(
		propagation.TraceContext{},
		propagation.Baggage{},
	))

	return func(ctx context.Context) error {
		var errs []error
		if err := tp.Shutdown(ctx); err != nil {
			errs = append(errs, fmt.Errorf("trace provider shutdown: %w", err))
		}
		if err := mp.Shutdown(ctx); err != nil {
			errs = append(errs, fmt.Errorf("meter provider shutdown: %w", err))
		}
		if err := lp.Shutdown(ctx); err != nil {
			errs = append(errs, fmt.Errorf("log provider shutdown: %w", err))
		}
		if len(errs) > 0 {
			return fmt.Errorf("telemetry shutdown errors: %v", errs)
		}

		return nil
	}, nil
}
