CREATE TABLE IF NOT EXISTS files (
	id TEXT PRIMARY KEY,
	file_name TEXT NOT NULL,
	file_size INTEGER NOT NULL,
	expiration_time TIMESTAMP NOT NULL,
	download_count INTEGER DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);