# Default configuration for iSRV

# friendly name for the server, used in the HTML title and also in logs and responses
serverName: "iSRV"

# frontend url of the server, used for generating links in responses. Should include protocol and port if not default
serverUrl: http://localhost:8080

# host and port to listen on
serverHost: 0.0.0.0
serverPort: 8080

# maximum file size in megabytes for uploads
maxFileSizeMb: 512

# minimum and maximum age of files in days before they are automatically deleted by the cleanup routine
# the minimum age can be overridden by a query parameter in the upload request, but the maximum age is fixed
minAgeDays: 30
maxAgeDays: 365

# length of randomly generated file ids
randomIdLength: 12

# Disables the index page that shows project information and help, among other things.
disableIndexPage: false
# Disables the upload page that allows users to upload files through a web form.
disableUploadPage: true

# URL and format for the favicon. If empty, no favicon will be served.
# Can be a local file path or remote URL.
# The URL will be fetched and cached on startup. 
faviconUrl: ""
faviconFormat: "png"

# storage configuration
storage:
  # supported types: local, s3
  type: local
  # for local storage, this is the directory where files will be saved. For S3, this is the base path within the bucket (can be empty)
  basePath: ./upload_data/
  # for S3 storage, these are the required credentials and settings. For local storage, these can be left empty
  accessKey: ""
  secretKey: ""
  bucketName: ""
  region: ""
  endpoint: ""

database:
  # supported types: sqlite, postgres
  type: sqlite
  
  # for sqlite, this is the DSN (Data Source Name) which specifies the file path and options. 
  # for postgres, this can be a connection string or a set of parameters.
  #
  # when set, the DSN overrides all other database settings.
  dsn: file:isrv.db?cache=shared&mode=rwc

  # database file path for sqlite
  filePath: ""

  # connection parameters for postgres. These can be left empty if using sqlite or if the DSN is set.
  host: ""
  port: 0
  user: ""
  password: ""
  dbName: ""

# rate limit configuration
# applies to upload, expire and delete endpoints, but not to download or index page
rateLimit:
  enabled: true
  requestsPerMinute: 30
  burstSize: 10 # number of requests allowed in a short burst before enforcing the rate limit
  whitelistIps: []
  # supported actions: 
  # "throttle" (respond with 429 Too Many Requests and a Retry-After header)
  # "block" (respond with 403 Forbidden and block the IP for a certain duration)
  # "none" (no action, just log the event)
  onLimitExceeded: "throttle"
  blockDuration: 15m # duration to block IPs that exceed the limit, only applicable if action is "block"

# logging configuration
logging:
  level: info
  logToFile: false
  path: ./isrv.log
  logIps: true
  logUploads: true

# cleanup configuration
cleanup:
  enabled: true
  interval: 1m

# enable debug mode for more verbose logging and additional information in responses
debug: false