// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/feature/s3/transfermanager"
	mock "github.com/stretchr/testify/mock"
)

// NewMockS3Uploader creates a new instance of MockS3Uploader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockS3Uploader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockS3Uploader {
	mock := &MockS3Uploader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockS3Uploader is an autogenerated mock type for the S3Uploader type
type MockS3Uploader struct {
	mock.Mock
}

type MockS3Uploader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockS3Uploader) EXPECT() *MockS3Uploader_Expecter {
	return &MockS3Uploader_Expecter{mock: &_m.Mock}
}

// UploadObject provides a mock function for the type MockS3Uploader
func (_mock *MockS3Uploader) UploadObject(ctx context.Context, input *transfermanager.UploadObjectInput, opts ...func(*transfermanager.Options)) (*transfermanager.UploadObjectOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UploadObject")
	}

	var r0 *transfermanager.UploadObjectOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *transfermanager.UploadObjectInput, ...func(*transfermanager.Options)) (*transfermanager.UploadObjectOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *transfermanager.UploadObjectInput, ...func(*transfermanager.Options)) *transfermanager.UploadObjectOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transfermanager.UploadObjectOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *transfermanager.UploadObjectInput, ...func(*transfermanager.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockS3Uploader_UploadObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadObject'
type MockS3Uploader_UploadObject_Call struct {
	*mock.Call
}

// UploadObject is a helper method to define mock.On call
//   - ctx context.Context
//   - input *transfermanager.UploadObjectInput
//   - opts ...func(*transfermanager.Options)
func (_e *MockS3Uploader_Expecter) UploadObject(ctx any, input any, opts ...any) *MockS3Uploader_UploadObject_Call {
	return &MockS3Uploader_UploadObject_Call{Call: _e.mock.On("UploadObject",
		append([]any{ctx, input}, opts...)...)}
}

func (_c *MockS3Uploader_UploadObject_Call) Run(run func(ctx context.Context, input *transfermanager.UploadObjectInput, opts ...func(*transfermanager.Options))) *MockS3Uploader_UploadObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *transfermanager.UploadObjectInput
		if args[1] != nil {
			arg1 = args[1].(*transfermanager.UploadObjectInput)
		}
		var arg2 []func(*transfermanager.Options)
		var variadicArgs []func(*transfermanager.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*transfermanager.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockS3Uploader_UploadObject_Call) Return(uploadObjectOutput *transfermanager.UploadObjectOutput, err error) *MockS3Uploader_UploadObject_Call {
	_c.Call.Return(uploadObjectOutput, err)
	return _c
}

func (_c *MockS3Uploader_UploadObject_Call) RunAndReturn(run func(ctx context.Context, input *transfermanager.UploadObjectInput, opts ...func(*transfermanager.Options)) (*transfermanager.UploadObjectOutput, error)) *MockS3Uploader_UploadObject_Call {
	_c.Call.Return(run)
	return _c
}
