// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/markhc/isrv/internal/models"
	"github.com/markhc/isrv/internal/storage"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Backend provides a mock function for the type MockStorage
func (_mock *MockStorage) Backend() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Backend")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockStorage_Backend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Backend'
type MockStorage_Backend_Call struct {
	*mock.Call
}

// Backend is a helper method to define mock.On call
func (_e *MockStorage_Expecter) Backend() *MockStorage_Backend_Call {
	return &MockStorage_Backend_Call{Call: _e.mock.On("Backend")}
}

func (_c *MockStorage_Backend_Call) Run(run func()) *MockStorage_Backend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_Backend_Call) Return(s string) *MockStorage_Backend_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockStorage_Backend_Call) RunAndReturn(run func() string) *MockStorage_Backend_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFile provides a mock function for the type MockStorage
func (_mock *MockStorage) DeleteFile(ctx context.Context, fileID string) error {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type MockStorage_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID string
func (_e *MockStorage_Expecter) DeleteFile(ctx any, fileID any) *MockStorage_DeleteFile_Call {
	return &MockStorage_DeleteFile_Call{Call: _e.mock.On("DeleteFile", ctx, fileID)}
}

func (_c *MockStorage_DeleteFile_Call) Run(run func(ctx context.Context, fileID string)) *MockStorage_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_DeleteFile_Call) Return(err error) *MockStorage_DeleteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_DeleteFile_Call) RunAndReturn(run func(ctx context.Context, fileID string) error) *MockStorage_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// FileExists provides a mock function for the type MockStorage
func (_mock *MockStorage) FileExists(ctx context.Context, fileID string) (bool, error) {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for FileExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_FileExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileExists'
type MockStorage_FileExists_Call struct {
	*mock.Call
}

// FileExists is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID string
func (_e *MockStorage_Expecter) FileExists(ctx any, fileID any) *MockStorage_FileExists_Call {
	return &MockStorage_FileExists_Call{Call: _e.mock.On("FileExists", ctx, fileID)}
}

func (_c *MockStorage_FileExists_Call) Run(run func(ctx context.Context, fileID string)) *MockStorage_FileExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_FileExists_Call) Return(b bool, err error) *MockStorage_FileExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockStorage_FileExists_Call) RunAndReturn(run func(ctx context.Context, fileID string) (bool, error)) *MockStorage_FileExists_Call {
	_c.Call.Return(run)
	return _c
}

// HealthCheck provides a mock function for the type MockStorage
func (_mock *MockStorage) HealthCheck(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_HealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheck'
type MockStorage_HealthCheck_Call struct {
	*mock.Call
}

// HealthCheck is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorage_Expecter) HealthCheck(ctx any) *MockStorage_HealthCheck_Call {
	return &MockStorage_HealthCheck_Call{Call: _e.mock.On("HealthCheck", ctx)}
}

func (_c *MockStorage_HealthCheck_Call) Run(run func(ctx context.Context)) *MockStorage_HealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_HealthCheck_Call) Return(err error) *MockStorage_HealthCheck_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_HealthCheck_Call) RunAndReturn(run func(ctx context.Context) error) *MockStorage_HealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function for the type MockStorage
func (_mock *MockStorage) Open(ctx context.Context, fileID string, brange *storage.ByteRange) (*storage.Object, error) {
	ret := _mock.Called(ctx, fileID, brange)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 *storage.Object
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *storage.ByteRange) (*storage.Object, error)); ok {
		return returnFunc(ctx, fileID, brange)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *storage.ByteRange) *storage.Object); ok {
		r0 = returnFunc(ctx, fileID, brange)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.Object)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *storage.ByteRange) error); ok {
		r1 = returnFunc(ctx, fileID, brange)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockStorage_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID string
//   - brange *storage.ByteRange
func (_e *MockStorage_Expecter) Open(ctx any, fileID any, brange any) *MockStorage_Open_Call {
	return &MockStorage_Open_Call{Call: _e.mock.On("Open", ctx, fileID, brange)}
}

func (_c *MockStorage_Open_Call) Run(run func(ctx context.Context, fileID string, brange *storage.ByteRange)) *MockStorage_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *storage.ByteRange
		if args[2] != nil {
			arg2 = args[2].(*storage.ByteRange)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_Open_Call) Return(object *storage.Object, err error) *MockStorage_Open_Call {
	_c.Call.Return(object, err)
	return _c
}

func (_c *MockStorage_Open_Call) RunAndReturn(run func(ctx context.Context, fileID string, brange *storage.ByteRange) (*storage.Object, error)) *MockStorage_Open_Call {
	_c.Call.Return(run)
	return _c
}

// PresignedURL provides a mock function for the type MockStorage
func (_mock *MockStorage) PresignedURL(ctx context.Context, file *models.File) (string, bool, error) {
	ret := _mock.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for PresignedURL")
	}

	var r0 string
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.File) (string, bool, error)); ok {
		return returnFunc(ctx, file)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.File) string); ok {
		r0 = returnFunc(ctx, file)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.File) bool); ok {
		r1 = returnFunc(ctx, file)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *models.File) error); ok {
		r2 = returnFunc(ctx, file)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockStorage_PresignedURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignedURL'
type MockStorage_PresignedURL_Call struct {
	*mock.Call
}

// PresignedURL is a helper method to define mock.On call
//   - ctx context.Context
//   - file *models.File
func (_e *MockStorage_Expecter) PresignedURL(ctx any, file any) *MockStorage_PresignedURL_Call {
	return &MockStorage_PresignedURL_Call{Call: _e.mock.On("PresignedURL", ctx, file)}
}

func (_c *MockStorage_PresignedURL_Call) Run(run func(ctx context.Context, file *models.File)) *MockStorage_PresignedURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.File
		if args[1] != nil {
			arg1 = args[1].(*models.File)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_PresignedURL_Call) Return(url string, ok bool, err error) *MockStorage_PresignedURL_Call {
	_c.Call.Return(url, ok, err)
	return _c
}

func (_c *MockStorage_PresignedURL_Call) RunAndReturn(run func(ctx context.Context, file *models.File) (string, bool, error)) *MockStorage_PresignedURL_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockStorage
func (_mock *MockStorage) Save(ctx context.Context, fileID string, r io.Reader, opts storage.SaveOptions) (string, error) {
	ret := _mock.Called(ctx, fileID, r, opts)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, storage.SaveOptions) (string, error)); ok {
		return returnFunc(ctx, fileID, r, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, storage.SaveOptions) string); ok {
		r0 = returnFunc(ctx, fileID, r, opts)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, io.Reader, storage.SaveOptions) error); ok {
		r1 = returnFunc(ctx, fileID, r, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockStorage_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID string
//   - r io.Reader
//   - opts storage.SaveOptions
func (_e *MockStorage_Expecter) Save(ctx any, fileID any, r any, opts any) *MockStorage_Save_Call {
	return &MockStorage_Save_Call{Call: _e.mock.On("Save", ctx, fileID, r, opts)}
}

func (_c *MockStorage_Save_Call) Run(run func(ctx context.Context, fileID string, r io.Reader, opts storage.SaveOptions)) *MockStorage_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 storage.SaveOptions
		if args[3] != nil {
			arg3 = args[3].(storage.SaveOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorage_Save_Call) Return(s string, err error) *MockStorage_Save_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStorage_Save_Call) RunAndReturn(run func(ctx context.Context, fileID string, r io.Reader, opts storage.SaveOptions) (string, error)) *MockStorage_Save_Call {
	_c.Call.Return(run)
	return _c
}
