// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	storage0 "cloud.google.com/go/storage"
	"github.com/markhc/isrv/internal/storage"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGCSBucket creates a new instance of MockGCSBucket. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGCSBucket(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGCSBucket {
	mock := &MockGCSBucket{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGCSBucket is an autogenerated mock type for the GCSBucket type
type MockGCSBucket struct {
	mock.Mock
}

type MockGCSBucket_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGCSBucket) EXPECT() *MockGCSBucket_Expecter {
	return &MockGCSBucket_Expecter{mock: &_m.Mock}
}

// DeleteObject provides a mock function for the type MockGCSBucket
func (_mock *MockGCSBucket) DeleteObject(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGCSBucket_DeleteObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObject'
type MockGCSBucket_DeleteObject_Call struct {
	*mock.Call
}

// DeleteObject is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockGCSBucket_Expecter) DeleteObject(ctx any, name any) *MockGCSBucket_DeleteObject_Call {
	return &MockGCSBucket_DeleteObject_Call{Call: _e.mock.On("DeleteObject", ctx, name)}
}

func (_c *MockGCSBucket_DeleteObject_Call) Run(run func(ctx context.Context, name string)) *MockGCSBucket_DeleteObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGCSBucket_DeleteObject_Call) Return(err error) *MockGCSBucket_DeleteObject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGCSBucket_DeleteObject_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockGCSBucket_DeleteObject_Call {
	_c.Call.Return(run)
	return _c
}

// NewRangeReader provides a mock function for the type MockGCSBucket
func (_mock *MockGCSBucket) NewRangeReader(ctx context.Context, name string, offset int64, length int64) (*storage.GCSReadResult, error) {
	ret := _mock.Called(ctx, name, offset, length)

	if len(ret) == 0 {
		panic("no return value specified for NewRangeReader")
	}

	var r0 *storage.GCSReadResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) (*storage.GCSReadResult, error)); ok {
		return returnFunc(ctx, name, offset, length)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) *storage.GCSReadResult); ok {
		r0 = returnFunc(ctx, name, offset, length)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.GCSReadResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, int64) error); ok {
		r1 = returnFunc(ctx, name, offset, length)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGCSBucket_NewRangeReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewRangeReader'
type MockGCSBucket_NewRangeReader_Call struct {
	*mock.Call
}

// NewRangeReader is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - offset int64
//   - length int64
func (_e *MockGCSBucket_Expecter) NewRangeReader(ctx any, name any, offset any, length any) *MockGCSBucket_NewRangeReader_Call {
	return &MockGCSBucket_NewRangeReader_Call{Call: _e.mock.On("NewRangeReader", ctx, name, offset, length)}
}

func (_c *MockGCSBucket_NewRangeReader_Call) Run(run func(ctx context.Context, name string, offset int64, length int64)) *MockGCSBucket_NewRangeReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGCSBucket_NewRangeReader_Call) Return(gCSReadResult *storage.GCSReadResult, err error) *MockGCSBucket_NewRangeReader_Call {
	_c.Call.Return(gCSReadResult, err)
	return _c
}

func (_c *MockGCSBucket_NewRangeReader_Call) RunAndReturn(run func(ctx context.Context, name string, offset int64, length int64) (*storage.GCSReadResult, error)) *MockGCSBucket_NewRangeReader_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockGCSBucket
func (_mock *MockGCSBucket) Ping(ctx context.Context, prefix string) error {
	ret := _mock.Called(ctx, prefix)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, prefix)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGCSBucket_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockGCSBucket_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
func (_e *MockGCSBucket_Expecter) Ping(ctx any, prefix any) *MockGCSBucket_Ping_Call {
	return &MockGCSBucket_Ping_Call{Call: _e.mock.On("Ping", ctx, prefix)}
}

func (_c *MockGCSBucket_Ping_Call) Run(run func(ctx context.Context, prefix string)) *MockGCSBucket_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGCSBucket_Ping_Call) Return(err error) *MockGCSBucket_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGCSBucket_Ping_Call) RunAndReturn(run func(ctx context.Context, prefix string) error) *MockGCSBucket_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// SignedURL provides a mock function for the type MockGCSBucket
func (_mock *MockGCSBucket) SignedURL(name string, opts *storage0.SignedURLOptions) (string, error) {
	ret := _mock.Called(name, opts)

	if len(ret) == 0 {
		panic("no return value specified for SignedURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *storage0.SignedURLOptions) (string, error)); ok {
		return returnFunc(name, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *storage0.SignedURLOptions) string); ok {
		r0 = returnFunc(name, opts)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, *storage0.SignedURLOptions) error); ok {
		r1 = returnFunc(name, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGCSBucket_SignedURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignedURL'
type MockGCSBucket_SignedURL_Call struct {
	*mock.Call
}

// SignedURL is a helper method to define mock.On call
//   - name string
//   - opts *storage0.SignedURLOptions
func (_e *MockGCSBucket_Expecter) SignedURL(name any, opts any) *MockGCSBucket_SignedURL_Call {
	return &MockGCSBucket_SignedURL_Call{Call: _e.mock.On("SignedURL", name, opts)}
}

func (_c *MockGCSBucket_SignedURL_Call) Run(run func(name string, opts *storage0.SignedURLOptions)) *MockGCSBucket_SignedURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *storage0.SignedURLOptions
		if args[1] != nil {
			arg1 = args[1].(*storage0.SignedURLOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGCSBucket_SignedURL_Call) Return(s string, err error) *MockGCSBucket_SignedURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGCSBucket_SignedURL_Call) RunAndReturn(run func(name string, opts *storage0.SignedURLOptions) (string, error)) *MockGCSBucket_SignedURL_Call {
	_c.Call.Return(run)
	return _c
}

// StatObject provides a mock function for the type MockGCSBucket
func (_mock *MockGCSBucket) StatObject(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for StatObject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGCSBucket_StatObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatObject'
type MockGCSBucket_StatObject_Call struct {
	*mock.Call
}

// StatObject is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockGCSBucket_Expecter) StatObject(ctx any, name any) *MockGCSBucket_StatObject_Call {
	return &MockGCSBucket_StatObject_Call{Call: _e.mock.On("StatObject", ctx, name)}
}

func (_c *MockGCSBucket_StatObject_Call) Run(run func(ctx context.Context, name string)) *MockGCSBucket_StatObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGCSBucket_StatObject_Call) Return(err error) *MockGCSBucket_StatObject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGCSBucket_StatObject_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockGCSBucket_StatObject_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function for the type MockGCSBucket
func (_mock *MockGCSBucket) Upload(ctx context.Context, name string, meta storage.GCSObjectMeta, r io.Reader) error {
	ret := _mock.Called(ctx, name, meta, r)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, storage.GCSObjectMeta, io.Reader) error); ok {
		r0 = returnFunc(ctx, name, meta, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGCSBucket_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockGCSBucket_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - meta storage.GCSObjectMeta
//   - r io.Reader
func (_e *MockGCSBucket_Expecter) Upload(ctx any, name any, meta any, r any) *MockGCSBucket_Upload_Call {
	return &MockGCSBucket_Upload_Call{Call: _e.mock.On("Upload", ctx, name, meta, r)}
}

func (_c *MockGCSBucket_Upload_Call) Run(run func(ctx context.Context, name string, meta storage.GCSObjectMeta, r io.Reader)) *MockGCSBucket_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 storage.GCSObjectMeta
		if args[2] != nil {
			arg2 = args[2].(storage.GCSObjectMeta)
		}
		var arg3 io.Reader
		if args[3] != nil {
			arg3 = args[3].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGCSBucket_Upload_Call) Return(err error) *MockGCSBucket_Upload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGCSBucket_Upload_Call) RunAndReturn(run func(ctx context.Context, name string, meta storage.GCSObjectMeta, r io.Reader) error) *MockGCSBucket_Upload_Call {
	_c.Call.Return(run)
	return _c
}
