// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"mime/multipart"
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// DeleteFile provides a mock function for the type MockStorage
func (_mock *MockStorage) DeleteFile(ctx context.Context, fileID string) error {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type MockStorage_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID string
func (_e *MockStorage_Expecter) DeleteFile(ctx interface{}, fileID interface{}) *MockStorage_DeleteFile_Call {
	return &MockStorage_DeleteFile_Call{Call: _e.mock.On("DeleteFile", ctx, fileID)}
}

func (_c *MockStorage_DeleteFile_Call) Run(run func(ctx context.Context, fileID string)) *MockStorage_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_DeleteFile_Call) Return(err error) *MockStorage_DeleteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_DeleteFile_Call) RunAndReturn(run func(ctx context.Context, fileID string) error) *MockStorage_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// FileExists provides a mock function for the type MockStorage
func (_mock *MockStorage) FileExists(ctx context.Context, fileID string) (bool, error) {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for FileExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_FileExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileExists'
type MockStorage_FileExists_Call struct {
	*mock.Call
}

// FileExists is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID string
func (_e *MockStorage_Expecter) FileExists(ctx interface{}, fileID interface{}) *MockStorage_FileExists_Call {
	return &MockStorage_FileExists_Call{Call: _e.mock.On("FileExists", ctx, fileID)}
}

func (_c *MockStorage_FileExists_Call) Run(run func(ctx context.Context, fileID string)) *MockStorage_FileExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_FileExists_Call) Return(b bool, err error) *MockStorage_FileExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockStorage_FileExists_Call) RunAndReturn(run func(ctx context.Context, fileID string) (bool, error)) *MockStorage_FileExists_Call {
	_c.Call.Return(run)
	return _c
}

// SaveFileUpload provides a mock function for the type MockStorage
func (_mock *MockStorage) SaveFileUpload(ctx context.Context, fileID string, file multipart.File, fileHeader *multipart.FileHeader) (string, error) {
	ret := _mock.Called(ctx, fileID, file, fileHeader)

	if len(ret) == 0 {
		panic("no return value specified for SaveFileUpload")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, multipart.File, *multipart.FileHeader) (string, error)); ok {
		return returnFunc(ctx, fileID, file, fileHeader)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, multipart.File, *multipart.FileHeader) string); ok {
		r0 = returnFunc(ctx, fileID, file, fileHeader)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, multipart.File, *multipart.FileHeader) error); ok {
		r1 = returnFunc(ctx, fileID, file, fileHeader)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_SaveFileUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveFileUpload'
type MockStorage_SaveFileUpload_Call struct {
	*mock.Call
}

// SaveFileUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID string
//   - file multipart.File
//   - fileHeader *multipart.FileHeader
func (_e *MockStorage_Expecter) SaveFileUpload(ctx interface{}, fileID interface{}, file interface{}, fileHeader interface{}) *MockStorage_SaveFileUpload_Call {
	return &MockStorage_SaveFileUpload_Call{Call: _e.mock.On("SaveFileUpload", ctx, fileID, file, fileHeader)}
}

func (_c *MockStorage_SaveFileUpload_Call) Run(run func(ctx context.Context, fileID string, file multipart.File, fileHeader *multipart.FileHeader)) *MockStorage_SaveFileUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 multipart.File
		if args[2] != nil {
			arg2 = args[2].(multipart.File)
		}
		var arg3 *multipart.FileHeader
		if args[3] != nil {
			arg3 = args[3].(*multipart.FileHeader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorage_SaveFileUpload_Call) Return(s string, err error) *MockStorage_SaveFileUpload_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStorage_SaveFileUpload_Call) RunAndReturn(run func(ctx context.Context, fileID string, file multipart.File, fileHeader *multipart.FileHeader) (string, error)) *MockStorage_SaveFileUpload_Call {
	_c.Call.Return(run)
	return _c
}

// ServeFile provides a mock function for the type MockStorage
func (_mock *MockStorage) ServeFile(w http.ResponseWriter, r *http.Request, fileID string, fileName string, metadata map[string]string, inlineContent bool, cachingEnabled bool) {
	_mock.Called(w, r, fileID, fileName, metadata, inlineContent, cachingEnabled)
	return
}

// MockStorage_ServeFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServeFile'
type MockStorage_ServeFile_Call struct {
	*mock.Call
}

// ServeFile is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - fileID string
//   - fileName string
//   - metadata map[string]string
//   - inlineContent bool
//   - cachingEnabled bool
func (_e *MockStorage_Expecter) ServeFile(w interface{}, r interface{}, fileID interface{}, fileName interface{}, metadata interface{}, inlineContent interface{}, cachingEnabled interface{}) *MockStorage_ServeFile_Call {
	return &MockStorage_ServeFile_Call{Call: _e.mock.On("ServeFile", w, r, fileID, fileName, metadata, inlineContent, cachingEnabled)}
}

func (_c *MockStorage_ServeFile_Call) Run(run func(w http.ResponseWriter, r *http.Request, fileID string, fileName string, metadata map[string]string, inlineContent bool, cachingEnabled bool)) *MockStorage_ServeFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 map[string]string
		if args[4] != nil {
			arg4 = args[4].(map[string]string)
		}
		var arg5 bool
		if args[5] != nil {
			arg5 = args[5].(bool)
		}
		var arg6 bool
		if args[6] != nil {
			arg6 = args[6].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockStorage_ServeFile_Call) Return() *MockStorage_ServeFile_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStorage_ServeFile_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request, fileID string, fileName string, metadata map[string]string, inlineContent bool, cachingEnabled bool)) *MockStorage_ServeFile_Call {
	_c.Run(run)
	return _c
}
