/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as PrivacyRouteImport } from "./routes/privacy"
import { Route as FaqRouteImport } from "./routes/faq"
import { Route as AdminRouteImport } from "./routes/admin"
import { Route as AbuseRouteImport } from "./routes/abuse"
import { Route as AboutRouteImport } from "./routes/about"
import { Route as IndexRouteImport } from "./routes/index"

const PrivacyRoute = PrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: "/faq",
  path: "/faq",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import("./routes/admin.lazy").then((d) => d.Route))
const AbuseRoute = AbuseRouteImport.update({
  id: "/abuse",
  path: "/abuse",
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/abuse": typeof AbuseRoute
  "/admin": typeof AdminRoute
  "/faq": typeof FaqRoute
  "/privacy": typeof PrivacyRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/abuse": typeof AbuseRoute
  "/admin": typeof AdminRoute
  "/faq": typeof FaqRoute
  "/privacy": typeof PrivacyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/abuse": typeof AbuseRoute
  "/admin": typeof AdminRoute
  "/faq": typeof FaqRoute
  "/privacy": typeof PrivacyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/about" | "/abuse" | "/admin" | "/faq" | "/privacy"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/about" | "/abuse" | "/admin" | "/faq" | "/privacy"
  id: "__root__" | "/" | "/about" | "/abuse" | "/admin" | "/faq" | "/privacy"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AbuseRoute: typeof AbuseRoute
  AdminRoute: typeof AdminRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/privacy": {
      id: "/privacy"
      path: "/privacy"
      fullPath: "/privacy"
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/faq": {
      id: "/faq"
      path: "/faq"
      fullPath: "/faq"
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin": {
      id: "/admin"
      path: "/admin"
      fullPath: "/admin"
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/abuse": {
      id: "/abuse"
      path: "/abuse"
      fullPath: "/abuse"
      preLoaderRoute: typeof AbuseRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/about": {
      id: "/about"
      path: "/about"
      fullPath: "/about"
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AbuseRoute: AbuseRoute,
  AdminRoute: AdminRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
