name: Go Build
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.25
    - name: Cache Go modules
      uses: actions/cache@v6
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: Install pnpm
      run: npm install -g pnpm
    
    - name: Get Cache Store Path
      run: |
        PNPM_STORE_PATH=$(pnpm store path)
        echo "PNPM_STORE_PATH=$PNPM_STORE_PATH" >> $GITHUB_ENV

    - name: Cache pnpm store
      uses: actions/cache@v6
      with:
        path: ${{ env.PNPM_STORE_PATH }}
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Build
      run: make build
    - name: Run tests
      run: make test